# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb64aea61a628fba505df0505fa85af5eadef8b72a85758ce7d3aeb0b473f489d63d34dec958783e33d25fe7a3bfe5f3487248aa746a5ebf299a23101907b99

test:
  secret_key_base: 167719794c3e10e6fb29131e9e062240bceb63af6833a2b5aa2b75bdcb7dba2d314babecf85e4cc93990d9040f520c4b820bb753dff543f4e988ce9674e83d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
